name: Publish container image
on:
  release:
    types: [released]
jobs:
  container_image_publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: carvidonet/push-to-ghcr@main
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
